services:
  message-service:
    hostname: message-service
    container_name: message-service
    build: 
      context: ../
      dockerfile: ./src/MessageService/docker/Dockerfile  
    expose:
      - 80
    ports:
      - "2847:80"
  message-service-postgres:
    hostname: message-service-postgres
    container_name: message-service-postgres
    build: ../src/MessageService/docker/postgres
    command: postgres -c 'max_connections=100'
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=P@ssWord1!
      - POSTGRES_DB=postgres
    volumes:
      - message-service-postgres-data:/var/lib/postgresql/data
  web-app:
    hostname: web-app
    container_name: web-app
    build:
      context: ../
      dockerfile: ./src/WebApp/docker/Dockerfile
    ports:
      - "2848:80"

volumes:
  message-service-postgres-data:

